const lines = ["You’re so hot, my zipper is falling for you.",
   "They say that kissing is a language of love, so would you mind starting a conversation with me?",
  "I’m on top of things. Would you like to be one of them?",
  "Are you an eco-friendly kind of girl? The condom in my pocket goes expires tomorrow, so why don’t you help me use it?",
  "Do you want to commit a sin for your next confessional?",
  "I’m not into watching sunsets, but I’d love to see you go down.",
  "Are you an exam? Because I have been studying you like crazy.",
  "Can you tell me what time you’ll come back to my place, please?",
  "Give me your body keys so I can drive you crazy.",
  "I love my bed, but I’d rather be in yours.",
  "Your body is 70 percent water… and I’m thirsty.",
  "Are you undressing me with your eyes?!",
  "Your outfit would look great on my bedroom floor.",
  "Is it hot in here? Or is it just you?",
  "I lost my keys… can I check your pants?",
  "Did you know my lips are like Skittles and you’re about to taste the rainbow?",
  "Do I have to sign for your package?",
  "I know a great way to burn off the calories in that drink.",
  "Please don’t let this go to your head, but do you want some?",
  "Are you an elevator? Because I’ll go up and down on you.",
  "You look great right now. Do you know what else would look great on you? Me!",
  "With school, I just want an A. With you, I just want to F.",
  "Did you have Lucky Charms for breakfast? Because you look magically delicious!",
"Roses are red. Violets are fine. You be the six. I’ll be the nine.",
"Do you drink soda? Because you look so-da-licious.",
"Do you have a shovel? Because I’m digging you.",
"What did you say your name was? I want to make sure I’m screaming the right name tonight.",
"That’s a nice shirt. Can I try it on after we have sex?",
"I think I could fall madly in bed with you.",
"Can I borrow a kiss? I promise I’ll give it back.", "Are you a campfire? Because you’re hot and I want s’more.",
"If you’re feeling down, I can feel you up.","What is a nice person like you doing in a dirty mind like mine?","We were both born without clothes.",
"I’m peanut butter. You’re jelly. Let’s have sex.",
"I’m not feeling myself today. Can I feel you instead?",
"I don’t think I want babies, but I wouldn’t mind refining my baby-making technique with you.",
"You know what winks and then screws like a tiger? (Wink)",
"My doctor told me I have a vitamin D deficiency. Want to go back to my place and save me?",
"Are you my homework? Because I’m not doing you, but I definitely should be.",
"Are you a drill sergeant? Because you have my privates standing at attention.",
"Can you do telekinesis? Because you’ve made a part of me move without even touching it.",
"Treat me like a pirate and give me that booty.",
"If you were a flower, you’d be a damn-delion.",
"Let’s play Titanic. You’ll be the iceberg and I’ll go down.","Dinner first, or can we go straight for dessert?",
"I was feeling very off today, but then you turned me on.",
"Does your name start with “C” because I can “C” us getting down.",
"I’m having trouble sleeping by myself. Can you sleep with me?",
"This might seem corny, but you’re making me horny.",
"Want to save water by showering together?",
"I’m an adventurer and I want to explore you.",
"Want to go half on a baby?",
"Do you have room for an extra tongue in your mouth?",
"Are you a supermarket sample? Because I want to taste you again and again without any sense of shame.",
"Are you a sea lion? Because I can sea you lion in my bed tonight.","Don’t ever change. Just get naked.","I’m just like a pore strip. Hard to get off, but extremely satisfied once you do.","You are so selfish. You’re going to have that body for the rest of your life and I just want it for one night.","Did you send the invitation to the party between your legs by mail, or do you wanna give it to me in person?","If I was the judge, I’d sentence you to my bed.","Is that a candy cane in your pocket or are you just happy to see me?","You must be yogurt because I want to spoon you.","Damn, if being sexy was a crime, you’d be guilty as charged!","Are you a trampoline? Because I want to bounce on you.","Let only latex stand between our love.","Do you like bacon? Wanna strip?","Your legs must be tired because you’ve been running through my mind all night.","Nice dress. Can I talk you out of it?","Can I borrow your lips?","There must be a light switch on my forehead because every time I see you, you turn me on!","So as long as we’re in the theatre… why don’t we get some play?","That shirt looks great on you… as a matter of fact, so would I.","Stop, drop, and roll, baby. You are on fire.","I think you’re suffering from a lack of vitamin me.","Baby, you’re so sweet, you put Hershey’s Kisses out of business.","Is that a mirror in your pants because I can see myself in them.","Want to play conductor? You be the engineer and I’ll go choo-choo.","If you look that good in clothes, you must look even better out of them.","Baby, you’re so hot, you make the equator look like the north pole.","Someone should call the police because you just stole my heart!","Sorry to bother you but: Do you have room for an extra tongue in your mouth?","Don’t ever change. Okay? Just get naked.","Don’t have a bike? You can mount me instead.","Can you tell me what time your legs open, please?","My nickname is dishes, because I want you to get me wet then do me.","I’m really good at math, so let’s add a bed, subtract our clothes, divide our legs, and multiply.","I’m really good at math, so let’s add a bed, subtract our clothes, divide our legs, and multiply.","I’m like a snowflake: beautiful, unique, and with one touch, you’ll feel how wet I am.","Can you poke my belly button…from the inside?","Would you kiss me in the rain? I want to get twice as wet.","Let’s play carpenter so I can nail you.","There are 206 bones in the human body, but I’d really like to have 207.","Are your legs tired? Because as long as I have a face, you’ll have a place to sit.","I’d love to get on my knees and show you my best donut smile.","If you were a balloon, I’d totally blow you.","I’m not a weather man, but I’m expecting a few more inches tonight.","Are you a firefighter? Because you make me hot and leave me wet.","Please don’t let this go to your head, but do you want some?","The only reason I would kick you out of bed would be to f*ck you on the floor.","I’d love to kiss your luscious lips…and then the ones on your face.","That shirt’s very becoming on you. If I were on you, I’d be coming too.","If I were you, I’d have sex with me.","Are you a haunted house? Because I’m going to scream when I’m in you.","Can you do telekinesis? Because you’ve made a part of me move without even touching it.","One of my friends told me girls hate oral, do you wanna help me prove him wrong?","Are you a drill sergeant? Because you have my privates standing at attention.","The FBI wants to steal my penis. Can I hide it inside you?"," I can see your pants swelling. We need to check immediately what is cooking in them.","Looking at you turns me on all the time"," The lack of your nudity in my mind is just exceptional.",
];
module.exports = {
  config: {
    name: "hornypickuplines",
    aliases: ["hornypickuplines"],
    version: "1.0",
    author: "Muhid", //do not change or modify credit.
    countDown: 5,
    role: 0,
    shortDescription: "Send a random hornypickup line",
    longDescription: "Sends a random hornypickup line",
    category: "𝗙𝗨𝗡",
    guide: {
      en: "{pn}",
    },
  },

  onStart: async function ({ message }) {
    const randomIndex = Math.floor(Math.random() * lines.length);
    const randomPickupLine = lines[randomIndex];

    message.reply(randomPickupLine);
  }
};
